### ISSUE TITLE
some question about QC

### ISSUE THREAD

**Issue by Dan-121** [mgheffel/snm3Cseq_feature_processing#1]
Hi, Matthew Heffel:
     You do a very good job, and thanks for the perfect work. I have some questions and please help me with these problems. Thanks a lot.
    1, What is bmCH mean? I can not find the definition on the web.
    2, What should I notice when I do the quality control of sn-m3C-seq datasets?
Thank you. Looking forward to your reply.

bmCH

**Comment by mgheffel** [comment]
Hi Dan,

Sorry about the confusion, I'll add a note defining bmCH/G in the writeup. bmCH stands for bin methylation CH as opposed to gene methylation CH. For this dataset in addition to calculation CH and CG methylation fractions across the gene bodies we also computed methylation fractions for 100kb bin across the entire genome, so that is what the bmCH and bmCG tags represent. Though it is worth noting that they are not required to execute this code.

When performing QC on snm3Cseq datasets I generally require the global methylation level per cell to be mCH/CH < 0.2, mCG/CG > 0.5, mCCC/CCC (this is the non-conversion rate) < 0.03, and often some cutoff related to read mapping rate/count, but that one may be more specific to the dataset.

Hope this helps. 
best,
Matthew G. Heffel

**Comment by Dan-121** [comment]
Thank you for your patient and in-time response and clear explanation. If I have any further questions, I will come back to bother you again. Once again, thank you for your excellent work.

**Comment by Dan-121** [comment]
Hi, I find that our data are available in the UCSC browser, Can you tell me what the exprMatrix.tsv.gz mean? since we have Methylation and 3C data.
Thank you. Looking forward to your reply.

**Comment by mgheffel** [comment]
Hi Dan, the filename is misleading and we will look to change that in the near future. The exprMatrix.tsv.gz file contains the gene body (+5kb flanking on both ends) methylation fractions calculated by mCH and mCG for features passing QC.

**Comment by Dan-121** [comment]
Thank you for your timely response. I really appreciate your help. To clarify, we used the methylation fractions for the gene body region with flanking sequences of +100kb on both sides for grouping purposes. However, for visualization purposes, we used the methylation fractions for the gene body region with flanking sequences of +5kb on both sides.
Thank you. Looking forward to your reply.
Dan

**Comment by mgheffel** [comment]
Hi Dan, 

If there was a question in there I'm not sure I understood it. Can you possibly ask in a different way?

**Comment by Dan-121** [comment]
Hi, Matthew Heffel:
    I apologize for any confusion in my previous response. What I meant was that we can cluster cells using the bmCG file, and then use the gmCG files to investigate interesting biological functions related to the identified cell types. 
   Thank you very much.Looking forward to your reply.
   Dan

**Comment by mgheffel** [comment]
Ah yes, we do that as well. We use the 100kb bins in clustering to gain additional information from the non-coding genome and then reduce the variables to gene body features for biological relevance.

For clarification, We cluster using BOTH 100kb bins and gene body methylation fractions.

**Comment by Dan-121** [comment]
Hello, Your work is truly outstanding, and I am grateful for your patience and wonderful response which has been incredibly helpful to me.

Once again, thank you for your exceptional work.
Dan
